/**
 * Class SWINGInteropEngine.NotificationRemoting
 * Generated by GenJava v 1.5.1273 and GenService v 1.5.1281.1
 * Tue Nov 18 14:05:48 PST 2003
 * Copyright (C) 2001, Intrinsyc Software Inc.  All rights reserved.
 */

package SWINGInteropEngine;

import com.intrinsyc.janet.*;
import com.intrinsyc.janet.remoting.ObjRef;


/**
 * This file is a Java proxy file generated by JaNET, the Java/.NET
 * integration product from Intrinsyc Software Inc.
 *
 * @author Ja.NET (GenJava tool)
 * @version 1.0
 */

public class NotificationRemoting extends RemoteProxy {


  /**
   * Constructor NotificationRemoting
   *
   * @param objRef
   *
   * throws RemoteException
   */
  public NotificationRemoting(ObjRef objRef) throws RemoteException {
    super(objRef);
  }

  // Void .ctor()

  /**
   * Constructor NotificationRemoting
   *
   * @throws RemoteException
   */
  public  NotificationRemoting() throws RemoteException  {
    super("SWINGInteropEngine.NotificationRemoting", "SWINGInteropEngineLibrary",
      new int[] {},
      new Object[] {},
      new String[] {});
  }

  // Void .ctor()

  /**
   * Constructor NotificationRemoting
   *
   * @param URI
   * @param format
   * @param clientActivated
   * @throws RemoteException
   */
  public  NotificationRemoting(String URI, String format, 
      boolean clientActivated) throws RemoteException  {
    super("SWINGInteropEngine.NotificationRemoting", "SWINGInteropEngineLibrary",
      URI, format, clientActivated,
      new int[] {},
      new Object[] {},
      new String[] {});
  }

  // System.String DisplayForm(System.String, System.String, System.Collections.ArrayList, System.Collections.ArrayList, System.String, Boolean)

  /**
   * Method DisplayForm
   *
   * @param assembly
   * @param form
   * @param keys
   * @param values
   * @param returnProperty
   * @param dialog
   * @return java.lang.String
   * @throws RemoteException
   */
  public java.lang.String DisplayForm(java.lang.String assembly, 
      java.lang.String form, java.util.List keys, java.util.List values, 
      java.lang.String returnProperty, boolean dialog) 
      throws RemoteException  {
    java.lang.String[] retval = new java.lang.String[1];

    invokeMethod("DisplayForm",
      new int[] {STRING, STRING, OBJECT_BY_VALUE, OBJECT_BY_VALUE, STRING, 
        BOOLEAN, STRING | RETURN},
      new Object[] {assembly, form, keys, values, returnProperty, 
        new Boolean(dialog), retval},
      new String[] {"System.String", "System.String", 
        "System.Collections.ArrayList", 
        "System.Collections.ArrayList", "System.String", 
        "System.Boolean", "System.String"});
    return retval[0];
  }


  // for internal use only

  /**
   * Constructor NotificationRemoting
   *
   * @param className
   * @param assembly
   * @param parameterTypes
   * @param parameterValues
   * @param parameterTypeNames
   *
   * @throws RemoteException
   *
   */
  protected NotificationRemoting(String className, String assembly,
        int[] parameterTypes, Object[] parameterValues,
        String[] parameterTypeNames) throws RemoteException {
    super(className, assembly, 
      parameterTypes, parameterValues, parameterTypeNames);
  }

  // for internal use only

  /**
   * Constructor NotificationRemoting
   *
   * @param className
   * @param assembly
   * @param URI
   * @param format
   * @param clientActivated
   * @param parameterTypes
   * @param parameterValues
   * @param parameterTypeNames
   *
   * @throws RemoteException
   */
  protected NotificationRemoting(String className, String assembly,
        String URI, String format, boolean clientActivated,
        int[] parameterTypes, Object[] parameterValues,
        String[] parameterTypeNames) throws RemoteException {
    super(className, assembly, URI, format, clientActivated,
      parameterTypes, parameterValues, parameterTypeNames);
  }

  public static final java.lang.String __janetAssemblyName = 
    "SWINGInteropEngineLibrary, Version=1.0.1417.25352, Culture=neutral, PublicKeyToken=null";
  public static final java.lang.String __janetClassName = 
    "SWINGInteropEngine.NotificationRemoting";

}
